import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Item from '../components/Item'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div className="max-w-6xl mx-auto">
      <Head>
        <title>Python Scripts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className='sticky top-0 z-20' >
      <Header/>
      </div>
      <Hero/>
      <Item/>
      <Footer/>
    </div>
  )
}
