'''Design a project where as an input student will give a static number (between 1 to 6) and then roll the dice which randomly generate some value between 1 to 6. The winning situation arrives when the given static/fixed number exactly same to the number came after rolling the dice.'''

import random
import time

def roll_dice():
    '''Rolls the dice and returns a random number between 1 and 6'''
    return random.randint(1, 6)

def main():
    '''Main function'''
    print('Welcome to the dice rolling game!')
    print('You will be asked to enter a number between 1 and 6.')
    print('The dice will be rolled and a random number between 1 and 6 will be generated.')
    print('If the number you entered is the same as the number generated by the dice, you win!')
    print('If not, you lose!')
    print('Good luck!')
    print()
    time.sleep(2)

    while True:
        try:
            number = int(input('Enter a number between 1 and 6: '))
            if number < 1 or number > 6:
                print('Number must be between 1 and 6!')
                continue
            break
        except ValueError:
            print('Invalid input!')
            continue
    print('Rolling the dice...')
    time.sleep(2)
    print('The value is:', roll_dice())
    if roll_dice() == number:
        print('You win!')
    else:
        print('You lose!')
        print('Better Luck next time :(')

if __name__ == '__main__':
    main()

